# -*- coding: utf-8 -*-
"""Report gen ViT-gpt2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/report-gen-vit-gpt2-48f948fd-0309-495a-8a71-50ccb9c03823.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240603/auto/storage/goog4_request%26X-Goog-Date%3D20240603T100537Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D4edcac2d61b00fc53f9a68de57a14f07c16f1c5b7989b5cea4a30fe6f5bd3e807f384a9f135eb5d8d1a9c73b4757dfdb476f320e0f9f598fddb8ae95b325f134944acd43bbbe0cd0a6b9b69fafa48b8929194470cb950390616a775eba0b07e3d13e572df1a3786d3576cd70a652abad6eaace8cdc2e2bb7fbeaa616f161475e962f106e4f8da09e18210261398bc2e2d0e3df30dd7cbe6d4efe9968047c074a21391fe167be1d029788f8f2618f1d72e35b039bde968085dab69b28f83cfd1f9b2defdbb31dd93e3124587869c8bb864172e8d174f1eeda1c37f1bce0b9f3c7574b05ae37238f54aa0ced079fdcd789717d797c18c3b38fe8fc12afbbbef90c
"""

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'chest-xrays-indiana-university:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F516716%2F951996%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240603%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240603T100537Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D126a57ea0f218abe81b2b2cafc5cbf95c5e3f58bb4afc517d554b2f9e9d51d415d770065560d512245e274026d0afa63b29d161adb92ed84a17817f7a22f3fda1ffe6643b498eac71199ec370c35762033df652951d3994c5ba425e6e69354aec27604ab7d72ba28590b13b92e351182d17a850d181f4a118db75aac0e9b88c5b5d0cdfe088e34391bff39c41d7dce2fb9eb5130b5a24eddf0fbc54fd8bf3b429ab8250772c15324ee5d191e916a8b2cb0422bb25a05320ed76b8549bcc6f8fe25adb9cee77ddccbe682b9afdd70203b03052c17b61efd38c544ed1bf8e5caa4817fc2e0121c810733b0fea5f451530633d56f16a60139e4aa59ba8989993a87'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')

"""# Import libraries"""

from transformers import (
    AutoFeatureExtractor,
    AutoTokenizer,
    VisionEncoderDecoderModel,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    default_data_collator,
)

from torch.utils.data import Dataset

import pandas as pd
from sklearn.model_selection import train_test_split

from pathlib import Path
from PIL import Image

"""# Import Data"""

df2 = pd.read_csv('/kaggle/input/chest-xrays-indiana-university/indiana_projections.csv')
df1 = pd.read_csv('/kaggle/input/chest-xrays-indiana-university/indiana_reports.csv')

"""# Creating Image, Caption Dictionary"""

images_captions_df = pd.DataFrame({'imgs': [],
                                    'captions': []})
for i in range(len(df2)):
    uid = df2.iloc[i]['uid']
    image = df2.iloc[i]['filename']
    index = df1.loc[df1['uid'] ==uid]

    if not index.empty:
        index = index.index[0]
        caption = df1.iloc[index]['findings']
        if type(caption) == float:

            continue
        images_captions_df = pd.concat([images_captions_df, pd.DataFrame([{'imgs': image, 'captions': caption}])], ignore_index=True)
images_captions_df.head()

"""# Set Encoder(ViT) Decoder(GPT2)"""

encoder_checkpoint = "google/vit-base-patch16-224-in21k"
decoder_checkpoint = "gpt2"

feature_extractor = AutoFeatureExtractor.from_pretrained(encoder_checkpoint)
tokenizer = AutoTokenizer.from_pretrained(decoder_checkpoint)
tokenizer.pad_token = tokenizer.eos_token

"""# Prepare the data"""

p = '/kaggle/input/chest-xrays-indiana-university/images/images_normalized/'
images_captions_df['imgs'] = p+ images_captions_df['imgs']
images_captions_df.head()

# maximum length for the captions
max_length = 512
sample = images_captions_df.iloc[99]

# sample image
image = Image.open(sample['imgs']).convert('RGB')
# sample caption
caption = sample['captions']

# apply feature extractor on the sample image
inputs = feature_extractor(images=image, return_tensors='pt')
# apply tokenizer
outputs = tokenizer(
            caption,
            max_length=max_length,
            truncation=True,
            padding='max_length',
            return_tensors='pt',
        )

print(f"Inputs:\n{inputs}\nOutputs:\n{outputs}")

class LoadDataset(Dataset):
    def __init__(self, df):
        self.images = images_captions_df['imgs'].values
        self.captions = images_captions_df['captions'].values


    def __getitem__(self, idx):
        # everything to return is stored inside this dict
        inputs = dict()

        # load the image and apply feature_extractor
        image_path = str(self.images[idx])
        image = Image.open(image_path).convert("RGB")
        image = feature_extractor(images=image, return_tensors='pt')

        # load the caption and apply tokenizer
        caption = self.captions[idx]
        labels = tokenizer(
            caption,
            max_length=max_length,
            truncation=True,
            padding='max_length',
            return_tensors='pt',
        )['input_ids'][0]

        # store the inputs and labels in the dict we created
        inputs['pixel_values'] = image['pixel_values'].squeeze()
        inputs['labels'] = labels
        return inputs

    def __len__(self):
        return len(self.images)

"""Split data: train,test,validation"""

# train_df, test_df = train_test_split(images_captions_df, test_size=0.20, shuffle=True, random_state=42)

train_,test_df =train_test_split(images_captions_df, test_size=0.10, shuffle=True, random_state=42)

print(len(train_))
# print(len(val_df))
print(len(test_df))

train_df,val_df =train_test_split(train_, test_size=0.10, shuffle=True, random_state=42)

print(len(train_df))
print(len(val_df))
print(len(test_df))

train_ds = LoadDataset(train_df)
test_ds = LoadDataset(test_df)
val_ds = LoadDataset(val_df)

test_df.head()

next(iter(test_ds))
# next(iter(val_ds))

"""# Prepare model"""

model = VisionEncoderDecoderModel.from_encoder_decoder_pretrained(
    encoder_checkpoint,
    decoder_checkpoint
)
model.config.decoder_start_token_id = tokenizer.bos_token_id
model.config.pad_token_id = tokenizer.pad_token_id
# model.config.vocab_size = model.config.decoder.vocab_size
model.config.num_beams = 4

batch = next(iter(train_ds))

model(pixel_values=batch['pixel_values'].unsqueeze(0), labels=batch['labels'].unsqueeze(0))

"""# Train model"""

training_args = Seq2SeqTrainingArguments(
    output_dir="image-caption-generator", # name of the directory to store training outputs
    evaluation_strategy="epoch",          # evaluate after each epoch
    per_device_train_batch_size=8,        # batch size during training
    per_device_eval_batch_size=8,         # batch size during evaluation
    learning_rate=5e-5,
    weight_decay=0.01,                    # weight decay for AdamW optimizer
    num_train_epochs=5,                   # number of epochs to train
    save_strategy='epoch',                # save checkpoints after each epoch
    report_to='none',                     # prevents logging to wandb, mlflow...
)

trainer = Seq2SeqTrainer(
    model=model,
    tokenizer=feature_extractor,
    data_collator=default_data_collator,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    args=training_args,
)

trainer.train()

"""### Save Model"""

import torch

FILE = '/kaggle/working/model.pth'

torch.save(model,FILE)

loaded_mode = torch.load(FILE)

torch.save(model.state_dict(), 'model_weights.pth')

model.load_state_dict(torch.load('model_weights.pth'))

trainer.save_model("/kaggle/working/")

"""# Push model to hugging face"""

from huggingface_hub import notebook_login

notebook_login()

#model.push_to_hub("Molkaatb/ChestX")

#trainer.push_to_hub("Molkaatb/ChestX")

"""### Inference"""

import torch
import matplotlib.pyplot as plt

inputs = val_ds[43]['pixel_values']
with torch.no_grad():
    # uncomment the below line if feature extractor is not applied to the image already
    # inputs = feature_extractor(images=inputs, return_tensors='pt').pixel_values

    # model prediction
    out = model.generate(
        inputs.unsqueeze(0).to('cuda'), # move inputs to GPU
        num_beams=4,
        max_length=512
        )


plt.axis('off')
plt.imshow(torch.permute(inputs, (1, 2, 0)));
# convert token ids to string format
decoded_out = tokenizer.decode(out[0], skip_special_tokens=True)
print(decoded_out)

"""### Show Original and Actual Imgs"""

import matplotlib.pyplot as plt
import torch

# Assuming you have a loop
for idx in range(40, 50):
    inputs = val_ds[idx]['pixel_values']
    with torch.no_grad():
        # Model prediction
        out = loaded_mode.generate(
            inputs.unsqueeze(0).to('cuda'),  # Move inputs to GPU
            num_beams=4,
            max_length=512
        )

    # Convert token ids to string format
    decoded_out = tokenizer.decode(out[0], skip_special_tokens=True)

    # Display the result
    print(f"Prediction for index {idx}: {decoded_out}")

    # Display the image
    plt.figure()
    plt.axis('off')
    plt.imshow(torch.permute(inputs, (1, 2, 0)))
    plt.show()

    print("\n\nActual Image and Text\n\n")
    # Display the text
    labels_tensor = val_ds[idx]['labels']

    decoded_out = tokenizer.decode(labels_tensor, skip_special_tokens=True)

    print(decoded_out)

    # Display actual image
    inputs = val_ds[idx]['pixel_values']

    # Convert the PyTorch tensor to a NumPy array
    image_array = inputs.permute(1, 2, 0).numpy()
    # Display the image using matplotlib
    plt.figure()
    plt.axis('off')
    plt.imshow(image_array)
    plt.show()

"""### Compute the BLEU score"""

import tqdm
predicted_captions = []
for i in tqdm.tqdm( val_df['imgs']):

    img =  Image.open(i).convert("RGB")
    caption = tokenizer.decode(model.generate(feature_extractor(img, return_tensors="pt").pixel_values.to("cuda"))[0],skip_special_tokens=True)
    predicted_captions.append(caption)
print(len(predicted_captions))

import nltk
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction

# Assuming you have a list of predicted captions and a list of ground truth captions
generated_captions = predicted_captions
ground_truth_captions = val_df['captions'].values
# Convert the caption lists into the format expected by nltk
ground_truth_captions = [[caption.split() for caption in captions] for captions in ground_truth_captions]
generated_captions = [caption.split() for caption in generated_captions]


# Define the smoothing function to use
smoothie = SmoothingFunction().method4

# Compute the BLEU score with smoothing
weights = (0.25, 0.25, 0.25, 0.25)  # equal weights for 1-4 gram BLEU scores
score = corpus_bleu(ground_truth_captions, predicted_captions,weights =weights)
print(f'The BELU Score Is: {score}')

"""### Save Model in .h5 Foramt"""

import h5py
import os
from pathlib import Path

# Convert PyTorch model parameters to NumPy arrays
model_dict = {key: value.cpu().numpy() for key, value in model.state_dict().items()}

# Specify the directory path
file_path = 'loadedd_model.h5'


# Save the parameters using h5py
with h5py.File(file_path, 'w') as hf:
    for key, value in model_dict.items():
        hf.create_dataset(key, data=value)

print(f'Model parameters saved to: {file_path}')

from IPython.display import FileLink

# Specify the file path in the Kaggle environment
kaggle_file_path = '/kaggle/working/loadedd_model.h5'

# Create a downloadable link
FileLink(kaggle_file_path)

"""# This is the link of the model pushed to the hugging face: https://huggingface.co/Molkaatb/ChestX"""